"""S2800/S3000/S3200 MIDI System Exclusive specification as structured data.

Every parameter, opcode, and protocol detail from the Akai S2800/S3000/S3200
SysEx specification encoded as Python dataclasses. This is the core knowledge
layer that agent tools query against.

Reference: https://lakai.sourceforge.net/docs/s2800_sysex.html
"""

from dataclasses import dataclass, field


@dataclass
class Parameter:
    """A single parameter in a header specification."""
    name: str
    offset: int
    size: int
    range_desc: str
    description: str
    models: list[str] = field(default_factory=lambda: ["S2800", "S3000", "S3200"])
    notes: str = ""


@dataclass
class HeaderSpec:
    """Specification for a header type (program, keygroup, or sample)."""
    name: str
    total_size: int
    request_opcode: int
    response_opcode: int
    parameters: list[Parameter] = field(default_factory=list)


@dataclass
class OpCode:
    """A SysEx operation code."""
    code: int
    name: str
    direction: str
    description: str
    selector_desc: str = ""


@dataclass
class ModulationSource:
    """A modulation source value."""
    value: int
    name: str
    description: str


@dataclass
class MiscDataType:
    """A miscellaneous data bank type."""
    bank: int
    name: str
    size: int
    description: str


# ---------------------------------------------------------------------------
# Modulation Sources
# ---------------------------------------------------------------------------

MODULATION_SOURCES = [
    ModulationSource(0, "No Source", "No modulation applied"),
    ModulationSource(1, "Modwheel", "MIDI CC1 modulation wheel (continuous)"),
    ModulationSource(2, "Bend", "Pitch bend wheel (continuous)"),
    ModulationSource(3, "Pressure", "Channel aftertouch / pressure (continuous)"),
    ModulationSource(4, "External", "External MIDI controller (continuous)"),
    ModulationSource(5, "Note-on velocity", "Velocity of the note-on event (fixed at note-on)"),
    ModulationSource(6, "Key", "MIDI note number / keyboard position (fixed at note-on)"),
    ModulationSource(7, "LFO1", "Low frequency oscillator 1 output"),
    ModulationSource(8, "LFO2", "Low frequency oscillator 2 output"),
    ModulationSource(9, "Env1", "Amplitude envelope (envelope 1) output"),
    ModulationSource(10, "Env2", "Filter envelope (envelope 2) output"),
    ModulationSource(11, "!Modwheel", "Instantaneous modwheel value captured at note-on"),
    ModulationSource(12, "!Bend", "Instantaneous pitch bend value captured at note-on"),
    ModulationSource(13, "!External", "Instantaneous external controller value captured at note-on"),
    ModulationSource(14, "Env3", "Auxiliary envelope (envelope 3) output"),
]

# ---------------------------------------------------------------------------
# Operation Codes
# ---------------------------------------------------------------------------

OPCODES = [
    OpCode(0x27, "Request Program Header", "request",
           "Request bytes from a program header",
           "Not used (set to 0)"),
    OpCode(0x28, "Program Header Data", "response",
           "Program header bytes (sent or received)",
           "Not used (set to 0)"),
    OpCode(0x29, "Request Keygroup Header", "request",
           "Request bytes from a keygroup header",
           "Keygroup number (0-based)"),
    OpCode(0x2A, "Keygroup Header Data", "response",
           "Keygroup header bytes (sent or received)",
           "Keygroup number (0-based)"),
    OpCode(0x2B, "Request Sample Header", "request",
           "Request bytes from a sample header",
           "Not used (set to 0)"),
    OpCode(0x2C, "Sample Header Data", "response",
           "Sample header bytes (sent or received)",
           "Not used (set to 0)"),
    OpCode(0x2D, "Request FX/Reverb", "request",
           "Request bytes from FX or reverb data",
           "0=FX header, 1=FX assign, 2=FX entry, 3=RVB assign, 4=RVB entry"),
    OpCode(0x2E, "FX/Reverb Data", "response",
           "FX or reverb data bytes (sent or received)",
           "0=FX header, 1=FX assign, 2=FX entry, 3=RVB assign, 4=RVB entry"),
    OpCode(0x2F, "Request Cue-List", "request",
           "Request bytes from a cue list",
           "0=header, 1=cue event"),
    OpCode(0x30, "Cue-List Data", "response",
           "Cue list data bytes (sent or received)",
           "0=header, 1=cue event"),
    OpCode(0x31, "Request Take List", "request",
           "Request bytes from a take list",
           "0=header, 1=take"),
    OpCode(0x32, "Take List Data", "response",
           "Take list data bytes (sent or received)",
           "0=header, 1=take"),
    OpCode(0x33, "Request Miscellaneous", "request",
           "Request miscellaneous data bytes",
           "Data bank type: 1=byte, 2=word, 3=dword, 4=smpte, 5=signed smpte, "
           "6=name, 7=16byteflag"),
    OpCode(0x34, "Miscellaneous Data", "response",
           "Miscellaneous data bytes (sent or received)",
           "Data bank type: 1=byte, 2=word, 3=dword, 4=smpte, 5=signed smpte, "
           "6=name, 7=16byteflag"),
    OpCode(0x35, "Request Volume List", "request",
           "Request a volume list entry",
           "Entry number"),
    OpCode(0x36, "Volume List Data", "response",
           "Volume list entry data (response only)",
           "Entry number"),
    OpCode(0x37, "Request HD Directory", "request",
           "Request a hard disk directory entry",
           "0=volume, 1=program, 2=sample, 3=cue list, 4=take list, "
           "5=effects file, 6=drum file"),
    OpCode(0x38, "HD Directory Data", "response",
           "Hard disk directory entry data (response only)",
           "0=volume, 1=program, 2=sample, 3=cue list, 4=take list, "
           "5=effects file, 6=drum file"),
]

# ---------------------------------------------------------------------------
# Miscellaneous Data Types
# ---------------------------------------------------------------------------

MISC_DATA_TYPES = [
    MiscDataType(1, "byte", 1, "Single byte value"),
    MiscDataType(2, "word", 2, "16-bit word value"),
    MiscDataType(3, "dword", 4, "32-bit double word value"),
    MiscDataType(4, "smpte", 5, "SMPTE time code (5 bytes)"),
    MiscDataType(5, "signed smpte", 5, "Signed SMPTE time code (5 bytes)"),
    MiscDataType(6, "name", 6, "Name string (6 bytes)"),
    MiscDataType(7, "16byteflag", 16, "16-byte flag field"),
]

# ---------------------------------------------------------------------------
# Program Header (192 bytes, opcode 0x27/0x28)
# ---------------------------------------------------------------------------

PROGRAM_HEADER = HeaderSpec(
    name="program",
    total_size=192,
    request_opcode=0x27,
    response_opcode=0x28,
    parameters=[
        Parameter("KGRP1@", 1, 2, "Block address",
                  "Block address of first keygroup (internal use, read-only)",
                  notes="Internal block address managed by the device"),
        Parameter("PRNAME", 3, 12, "Akai string (12 chars)",
                  "Name of program"),
        Parameter("PRGNUM", 15, 1, "0-128",
                  "MIDI program number"),
        Parameter("PMCHAN", 16, 1, "255=OMNI, 0-15",
                  "MIDI channel"),
        Parameter("POLYPH", 17, 1, "0-31 (represents 1-32 voices)",
                  "Depth of polyphony"),
        Parameter("PRIORT", 18, 1, "0=low, 1=norm, 2=high, 3=hold",
                  "Priority of voices when polyphony is exceeded"),
        Parameter("PLAYLO", 19, 1, "21-127 (A1-G8)",
                  "Lower limit of play range"),
        Parameter("PLAYHI", 20, 1, "21-127 (A1-G8)",
                  "Upper limit of play range"),
        Parameter("OSHIFT", 21, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("OUTPUT", 22, 1, "S3200: 0-10; S3000: 0-8; S2800: 0-2",
                  "Output routing / FX send",
                  notes="S2800: 0=out1, 1=out2, 2=FX. "
                        "S3000: 0-7=outputs 1-8, 8=FX. "
                        "S3200: 0-7=outputs, 8=FX, 9=RVB, 10=R+F"),
        Parameter("STEREO", 23, 1, "0-99",
                  "Left/right output levels"),
        Parameter("PANPOS", 24, 1, "-50 to +50",
                  "Balance between left and right outputs"),
        Parameter("PRLOUD", 25, 1, "0-99",
                  "Basic program loudness"),
        Parameter("V_LOUD", 26, 1, "-50 to +50",
                  "Velocity dependence of loudness"),
        Parameter("K_LOUD", 27, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("P_LOUD", 28, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("PANRAT", 29, 1, "0-99",
                  "Speed of LFO2 (pan LFO)"),
        Parameter("PANDEP", 30, 1, "0-99",
                  "Depth of LFO2 (pan LFO)"),
        Parameter("PANDEL", 31, 1, "0-99",
                  "Delay in growth of LFO2"),
        Parameter("K_PANP", 32, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("LFORAT", 33, 1, "0-99",
                  "Speed of LFO1 (pitch/filter LFO)"),
        Parameter("LFODEP", 34, 1, "0-99",
                  "Depth of LFO1"),
        Parameter("LFODEL", 35, 1, "0-99",
                  "Delay in growth of LFO1"),
        Parameter("MWLDEP", 36, 1, "0-99",
                  "Control of LFO1 depth by modulation wheel"),
        Parameter("PRSDEP", 37, 1, "0-99",
                  "Control of LFO1 depth by aftertouch pressure"),
        Parameter("VELDEP", 38, 1, "0-99",
                  "Control of LFO1 depth by note-on velocity"),
        Parameter("B_PTCH", 39, 1, "0-24 semitones",
                  "Range of pitch increase by bend wheel up"),
        Parameter("P_PTCH", 40, 1, "-12 to +12 semitones",
                  "Control of pitch by aftertouch pressure"),
        Parameter("KXFADE", 41, 1, "0=OFF, 1=ON",
                  "Keygroup crossfade enable"),
        Parameter("GROUPS", 42, 1, "1-99",
                  "Number of keygroups in this program",
                  notes="Read-only; managed by device"),
        Parameter("TPNUM", 43, 1, "0-127",
                  "Temporary program number (internal use)"),
        Parameter("TEMPER", 44, 12, "-50 to +50 cents per note",
                  "Key temperament offsets for C, C#, D, D#, E, F, F#, G, G#, A, A#, B"),
        Parameter("ECHOUT", 56, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("MW_PAN", 57, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("COHERE", 58, 1, "1",
                  "Not used",
                  notes="Reserved, always 1"),
        Parameter("DESYNC", 59, 1, "0=OFF, 1=ON",
                  "Desynchronization of LFO1 across simultaneous notes"),
        Parameter("PLAW", 60, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("VASSOQ", 61, 1, "0=OLDEST, 1=QUIETEST",
                  "Criterion for voice stealing when polyphony exceeded"),
        Parameter("SPLOUD", 62, 1, "0-99",
                  "Loudness reduction due to soft pedal"),
        Parameter("SPATT", 63, 1, "0-99",
                  "Attack stretch due to soft pedal"),
        Parameter("SPFILT", 64, 1, "0-99",
                  "Filter frequency reduction due to soft pedal"),
        Parameter("PTUNO", 65, 2, "-50.00 to +50.00",
                  "Program tuning offset in semitones and cents"),
        Parameter("K_LRAT", 67, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("K_LDEP", 68, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("K_LDEL", 69, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("VOSCL", 70, 1, "0-99",
                  "Level sent to outputs/effects"),
        Parameter("VSSCL", 71, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("LEGATO", 72, 1, "0=OFF, 1=ON",
                  "Mono legato mode"),
        Parameter("B_PTCHD", 73, 1, "0-12 semitones",
                  "Range of pitch decrease by bend wheel down"),
        Parameter("B_MODE", 74, 1, "0=NORMAL, 1=HELD",
                  "Whether bend affects held (sustained) notes"),
        Parameter("TRANSPOSE", 75, 1, "-50 to +50 semitones",
                  "Shift pitch of incoming MIDI notes"),
        Parameter("MODSPAN1", 76, 1, "Mod source (0-14)",
                  "Source 1 of assignable pan modulation"),
        Parameter("MODSPAN2", 77, 1, "Mod source (0-14)",
                  "Source 2 of assignable pan modulation"),
        Parameter("MODSPAN3", 78, 1, "Mod source (0-14)",
                  "Source 3 of assignable pan modulation"),
        Parameter("MODSAMP1", 79, 1, "Mod source (0-14)",
                  "Source 1 of assignable loudness modulation"),
        Parameter("MODSAMP2", 80, 1, "Mod source (0-14)",
                  "Source 2 of assignable loudness modulation"),
        Parameter("MODSLFOT", 81, 1, "Mod source (0-14)",
                  "Source of assignable LFO1 speed modulation"),
        Parameter("MODSLFOL", 82, 1, "Mod source (0-14)",
                  "Source of assignable LFO1 depth modulation"),
        Parameter("MODSLFOD", 83, 1, "Mod source (0-14)",
                  "Source of assignable LFO1 delay modulation"),
        Parameter("MODSFILT1", 84, 1, "Mod source (0-14)",
                  "Source 1 of assignable filter frequency modulation"),
        Parameter("MODSFILT2", 85, 1, "Mod source (0-14)",
                  "Source 2 of assignable filter frequency modulation"),
        Parameter("MODSFILT3", 86, 1, "Mod source (0-14)",
                  "Source 3 of assignable filter frequency modulation"),
        Parameter("MODSPITCH", 87, 1, "Mod source (0-14)",
                  "Source of assignable pitch modulation"),
        Parameter("MODSAMP3", 88, 1, "Mod source (0-14)",
                  "Source 3 of assignable loudness modulation"),
        Parameter("MODVPAN1", 89, 1, "-50 to +50",
                  "Amount of pan control by assignable source 1"),
        Parameter("MODVPAN2", 90, 1, "-50 to +50",
                  "Amount of pan control by assignable source 2"),
        Parameter("MODVPAN3", 91, 1, "-50 to +50",
                  "Amount of pan control by assignable source 3"),
        Parameter("MODVAMP1", 92, 1, "-50 to +50",
                  "Amount of loudness control by assignable source 1"),
        Parameter("MODVAMP2", 93, 1, "-50 to +50",
                  "Amount of loudness control by assignable source 2"),
        Parameter("MODVLFOR", 94, 1, "-50 to +50",
                  "Amount of LFO1 speed control by assignable source"),
        Parameter("MODVLVOL", 95, 1, "-50 to +50",
                  "Amount of LFO1 depth control by assignable source"),
        Parameter("MODVLFOD", 96, 1, "-50 to +50",
                  "Amount of LFO1 delay control by assignable source"),
        Parameter("LFO1WAVE", 97, 1, "0=Triangle, 1=Sawtooth, 2=Square",
                  "LFO1 waveform shape"),
        Parameter("LFO2WAVE", 98, 1, "0=Triangle, 1=Sawtooth, 2=Square",
                  "LFO2 waveform shape"),
        Parameter("MODSLFLT2_1", 99, 1, "Mod source (0-14)",
                  "Source 1 of filter 2 frequency modulation",
                  models=["S3200"],
                  notes="S3200 only; second filter modulation source"),
        Parameter("MODSLFLT2_2", 100, 1, "Mod source (0-14)",
                  "Source 2 of filter 2 frequency modulation",
                  models=["S3200"],
                  notes="S3200 only; second filter modulation source"),
        Parameter("MODSLFLT2_3", 101, 1, "Mod source (0-14)",
                  "Source 3 of filter 2 frequency modulation",
                  models=["S3200"],
                  notes="S3200 only; second filter modulation source"),
        Parameter("lfo2trig", 102, 1, "0-1",
                  "Retrigger mode for LFO2"),
        Parameter("PORTIME", 110, 1, "0-99",
                  "Portamento time"),
        Parameter("PORTYPE", 111, 1, "0=Rate, 1=Time",
                  "Portamento type"),
        Parameter("PORTEN", 112, 1, "0=OFF, 1=ON",
                  "Portamento enable"),
        Parameter("PFXCHAN", 113, 1, "0-4",
                  "Effects bus select",
                  notes="0=OFF, 1=FX1, 2=FX2, 3=RV3, 4=RV4"),
        Parameter("PFXSLEV", 114, 1, "0-99",
                  "Effects send level",
                  notes="Not used on some models"),
    ],
)

# ---------------------------------------------------------------------------
# Keygroup Header (192 bytes, opcode 0x29/0x2A)
# ---------------------------------------------------------------------------

KEYGROUP_HEADER = HeaderSpec(
    name="keygroup",
    total_size=192,
    request_opcode=0x29,
    response_opcode=0x2A,
    parameters=[
        # Basic keygroup identification
        Parameter("KGIDENT", 0, 1, "2 (fixed)",
                  "Block identifier for keygroup blocks",
                  notes="Always 2; identifies this block as a keygroup"),
        Parameter("NXTKG@", 1, 2, "Block address",
                  "Next keygroup block address (internal use)",
                  notes="Internal block address managed by device"),
        Parameter("LONOTE", 3, 1, "21-127 (A1-G8)",
                  "Lower limit of key range"),
        Parameter("HINOTE", 4, 1, "21-127 (A1-G8)",
                  "Upper limit of key range"),
        Parameter("KGTUNO", 5, 2, "-50.00 to +50.00",
                  "Keygroup tuning offset in semitones and cents"),
        Parameter("FILFRQ", 7, 1, "0-99",
                  "Basic filter frequency"),
        Parameter("K_FREQ", 8, 1, "0-12 semitones",
                  "Key follow of filter frequency"),
        Parameter("V_FREQ", 9, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("P_FREQ", 10, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("E_FREQ", 11, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        # Envelope 1 (amplitude)
        Parameter("ATTAK1", 12, 1, "0-99",
                  "Attack rate of envelope 1 (amplitude)"),
        Parameter("DECAY1", 13, 1, "0-99",
                  "Decay rate of envelope 1"),
        Parameter("SUSTN1", 14, 1, "0-99",
                  "Sustain level of envelope 1"),
        Parameter("RELSE1", 15, 1, "0-99",
                  "Release rate of envelope 1"),
        Parameter("V_ATT1", 16, 1, "-50 to +50",
                  "Velocity dependence of envelope 1 attack rate"),
        Parameter("V_REL1", 17, 1, "-50 to +50",
                  "Velocity dependence of envelope 1 release rate"),
        Parameter("O_REL1", 18, 1, "-50 to +50",
                  "Note-off velocity dependence of envelope 1 release"),
        Parameter("K_DAR1", 19, 1, "-50 to +50",
                  "Key dependence of envelope 1 decay and release rates"),
        # Envelope 2 (filter)
        Parameter("ATTAK2", 20, 1, "0-99",
                  "Attack rate of envelope 2 (filter)",
                  notes="Also known as ENV2R1 in extended envelope mode"),
        Parameter("DECAY2", 21, 1, "0-99",
                  "Decay rate of envelope 2",
                  notes="Also known as ENV2R3 in extended envelope mode"),
        Parameter("SUSTN2", 22, 1, "0-99",
                  "Sustain level of envelope 2",
                  notes="Also known as ENV2L3 in extended envelope mode"),
        Parameter("RELSE2", 23, 1, "0-99",
                  "Release rate of envelope 2",
                  notes="Also known as ENV2R4 in extended envelope mode"),
        Parameter("V_ATT2", 24, 1, "-50 to +50",
                  "Velocity dependence of envelope 2 attack rate"),
        Parameter("V_REL2", 25, 1, "-50 to +50",
                  "Velocity dependence of envelope 2 release rate"),
        Parameter("O_REL2", 26, 1, "-50 to +50",
                  "Note-off velocity dependence of envelope 2 release"),
        Parameter("K_DAR2", 27, 1, "-50 to +50",
                  "Key dependence of envelope 2 decay and release rates"),
        Parameter("V_ENV2", 28, 1, "-50 to +50",
                  "Scaling of envelope 2 depth by velocity"),
        Parameter("E_PTCH", 29, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("VXFADE", 30, 1, "0=OFF, 1=ON",
                  "Velocity zone crossfade enable"),
        Parameter("VZONES", 31, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("LKXF", 32, 1, "0-255",
                  "Calculated left keygroup crossfade factor (internal)",
                  notes="Internal; managed by device"),
        Parameter("RKXF", 33, 1, "0-255",
                  "Calculated right keygroup crossfade factor (internal)",
                  notes="Internal; managed by device"),
        # Velocity Zone 1 (offsets 34-57)
        Parameter("SNAME1", 34, 12, "Akai string (12 chars)",
                  "Sample name assigned to velocity zone 1"),
        Parameter("LOVEL1", 46, 1, "0-127",
                  "Lower limit of velocity range for zone 1"),
        Parameter("HIVEL1", 47, 1, "0-127",
                  "Upper limit of velocity range for zone 1"),
        Parameter("VTUNO1", 48, 2, "-50.00 to +50.00",
                  "Tuning offset for velocity zone 1"),
        Parameter("VLOUD1", 50, 1, "-50 to +50",
                  "Loudness offset for velocity zone 1"),
        Parameter("VFREQ1", 51, 1, "-50 to +50",
                  "Filter frequency offset for velocity zone 1"),
        Parameter("VPANO1", 52, 1, "-50 to +50",
                  "Pan offset for velocity zone 1"),
        Parameter("ZPLAY1", 53, 1, "0-4",
                  "Playback type for zone 1",
                  notes="0=As sample, 1=Loop in release, 2=Loop til release, "
                        "3=No loops, 4=Play to end"),
        Parameter("LVXF1", 54, 1, "0-255",
                  "Low velocity crossfade factor for zone 1 (internal)",
                  notes="Internal; managed by device"),
        Parameter("HVXF1", 55, 1, "0-255",
                  "High velocity crossfade factor for zone 1 (internal)",
                  notes="Internal; managed by device"),
        Parameter("SBADD1", 56, 2, "Block address",
                  "Sample header block address for zone 1 (internal)",
                  notes="Internal; managed by device"),
        # Velocity Zone 2 (offsets 58-81)
        Parameter("SNAME2", 58, 12, "Akai string (12 chars)",
                  "Sample name assigned to velocity zone 2"),
        Parameter("LOVEL2", 70, 1, "0-127",
                  "Lower limit of velocity range for zone 2"),
        Parameter("HIVEL2", 71, 1, "0-127",
                  "Upper limit of velocity range for zone 2"),
        Parameter("VTUNO2", 72, 2, "-50.00 to +50.00",
                  "Tuning offset for velocity zone 2"),
        Parameter("VLOUD2", 74, 1, "-50 to +50",
                  "Loudness offset for velocity zone 2"),
        Parameter("VFREQ2", 75, 1, "-50 to +50",
                  "Filter frequency offset for velocity zone 2"),
        Parameter("VPANO2", 76, 1, "-50 to +50",
                  "Pan offset for velocity zone 2"),
        Parameter("ZPLAY2", 77, 1, "0-4",
                  "Playback type for zone 2",
                  notes="0=As sample, 1=Loop in release, 2=Loop til release, "
                        "3=No loops, 4=Play to end"),
        Parameter("LVXF2", 78, 1, "0-255",
                  "Low velocity crossfade factor for zone 2 (internal)",
                  notes="Internal; managed by device"),
        Parameter("HVXF2", 79, 1, "0-255",
                  "High velocity crossfade factor for zone 2 (internal)",
                  notes="Internal; managed by device"),
        Parameter("SBADD2", 80, 2, "Block address",
                  "Sample header block address for zone 2 (internal)",
                  notes="Internal; managed by device"),
        # Velocity Zone 3 (offsets 82-105)
        Parameter("SNAME3", 82, 12, "Akai string (12 chars)",
                  "Sample name assigned to velocity zone 3"),
        Parameter("LOVEL3", 94, 1, "0-127",
                  "Lower limit of velocity range for zone 3"),
        Parameter("HIVEL3", 95, 1, "0-127",
                  "Upper limit of velocity range for zone 3"),
        Parameter("VTUNO3", 96, 2, "-50.00 to +50.00",
                  "Tuning offset for velocity zone 3"),
        Parameter("VLOUD3", 98, 1, "-50 to +50",
                  "Loudness offset for velocity zone 3"),
        Parameter("VFREQ3", 99, 1, "-50 to +50",
                  "Filter frequency offset for velocity zone 3"),
        Parameter("VPANO3", 100, 1, "-50 to +50",
                  "Pan offset for velocity zone 3"),
        Parameter("ZPLAY3", 101, 1, "0-4",
                  "Playback type for zone 3",
                  notes="0=As sample, 1=Loop in release, 2=Loop til release, "
                        "3=No loops, 4=Play to end"),
        Parameter("LVXF3", 102, 1, "0-255",
                  "Low velocity crossfade factor for zone 3 (internal)",
                  notes="Internal; managed by device"),
        Parameter("HVXF3", 103, 1, "0-255",
                  "High velocity crossfade factor for zone 3 (internal)",
                  notes="Internal; managed by device"),
        Parameter("SBADD3", 104, 2, "Block address",
                  "Sample header block address for zone 3 (internal)",
                  notes="Internal; managed by device"),
        # Velocity Zone 4 (offsets 106-129)
        Parameter("SNAME4", 106, 12, "Akai string (12 chars)",
                  "Sample name assigned to velocity zone 4"),
        Parameter("LOVEL4", 118, 1, "0-127",
                  "Lower limit of velocity range for zone 4"),
        Parameter("HIVEL4", 119, 1, "0-127",
                  "Upper limit of velocity range for zone 4"),
        Parameter("VTUNO4", 120, 2, "-50.00 to +50.00",
                  "Tuning offset for velocity zone 4"),
        Parameter("VLOUD4", 122, 1, "-50 to +50",
                  "Loudness offset for velocity zone 4"),
        Parameter("VFREQ4", 123, 1, "-50 to +50",
                  "Filter frequency offset for velocity zone 4"),
        Parameter("VPANO4", 124, 1, "-50 to +50",
                  "Pan offset for velocity zone 4"),
        Parameter("ZPLAY4", 125, 1, "0-4",
                  "Playback type for zone 4",
                  notes="0=As sample, 1=Loop in release, 2=Loop til release, "
                        "3=No loops, 4=Play to end"),
        Parameter("LVXF4", 126, 1, "0-255",
                  "Low velocity crossfade factor for zone 4 (internal)",
                  notes="Internal; managed by device"),
        Parameter("HVXF4", 127, 1, "0-255",
                  "High velocity crossfade factor for zone 4 (internal)",
                  notes="Internal; managed by device"),
        Parameter("SBADD4", 128, 2, "Block address",
                  "Sample header block address for zone 4 (internal)",
                  notes="Internal; managed by device"),
        # Common keygroup parameters
        Parameter("KBEAT", 130, 1, "-50 to +50",
                  "Fixed rate detune (beat frequency)"),
        Parameter("AHOLD", 131, 1, "0=OFF, 1=ON",
                  "Remain in attack phase until first loop point reached"),
        Parameter("CP1", 132, 1, "0=TRACK, 1=CONST",
                  "Constant pitch flag for velocity zone 1"),
        Parameter("CP2", 133, 1, "0=TRACK, 1=CONST",
                  "Constant pitch flag for velocity zone 2"),
        Parameter("CP3", 134, 1, "0=TRACK, 1=CONST",
                  "Constant pitch flag for velocity zone 3"),
        Parameter("CP4", 135, 1, "0=TRACK, 1=CONST",
                  "Constant pitch flag for velocity zone 4"),
        Parameter("VZOUT1", 136, 1, "S3000/S3200: 0-10; S2800: 0-4",
                  "Individual output routing for velocity zone 1",
                  notes="S2800 has fewer outputs than S3000/S3200"),
        Parameter("VZOUT2", 137, 1, "S3000/S3200: 0-10; S2800: 0-4",
                  "Individual output routing for velocity zone 2",
                  notes="S2800 has fewer outputs than S3000/S3200"),
        Parameter("VZOUT3", 138, 1, "S3000/S3200: 0-10; S2800: 0-4",
                  "Individual output routing for velocity zone 3",
                  notes="S2800 has fewer outputs than S3000/S3200"),
        Parameter("VZOUT4", 139, 1, "S3000/S3200: 0-10; S2800: 0-4",
                  "Individual output routing for velocity zone 4",
                  notes="S2800 has fewer outputs than S3000/S3200"),
        Parameter("VSS1", 140, 2, "-9999 to +9999",
                  "Sample start point velocity dependence for zone 1"),
        Parameter("VSS2", 142, 2, "-9999 to +9999",
                  "Sample start point velocity dependence for zone 2"),
        Parameter("VSS3", 144, 2, "-9999 to +9999",
                  "Sample start point velocity dependence for zone 3"),
        Parameter("VSS4", 146, 2, "-9999 to +9999",
                  "Sample start point velocity dependence for zone 4"),
        Parameter("KV_LO", 148, 1, "0",
                  "Not used",
                  notes="Reserved, always 0"),
        Parameter("FILQ", 149, 1, "0-15",
                  "Resonance of filter 1"),
        Parameter("L_PTCH", 150, 1, "-50 to +50",
                  "Control of pitch by LFO1"),
        Parameter("MODVFILT1", 151, 1, "-50 to +50",
                  "Control of filter frequency by assignable source 1"),
        Parameter("MODVFILT2", 152, 1, "-50 to +50",
                  "Control of filter frequency by assignable source 2"),
        Parameter("MODVFILT3", 153, 1, "-50 to +50",
                  "Control of filter frequency by assignable source 3"),
        Parameter("MODVPITCH", 154, 1, "-50 to +50",
                  "Control of pitch by assignable source"),
        Parameter("MODVAMP3", 155, 1, "-50 to +50",
                  "Control of loudness by assignable source 3"),
        # Extended envelope 2 parameters
        Parameter("ENV2L1", 156, 1, "0-99",
                  "Envelope 2 level at end of phase 1 (attack target)"),
        Parameter("ENV2R2", 157, 1, "0-99",
                  "Rate during phase 2 of envelope 2"),
        Parameter("ENV2L2", 158, 1, "0-99",
                  "Level of envelope 2 at end of phase 2"),
        Parameter("ENV2L4", 159, 1, "0-99",
                  "Final envelope 2 level (release target)"),
        Parameter("kgmute", 160, 1, "0xFF=OFF, 0-31",
                  "Keygroup mute group assignment",
                  notes="0xFF disables mute group; 0-31 assigns to a group"),
        Parameter("KFXCHAN", 161, 1, "0-4",
                  "Effects bus select (keygroup level)",
                  notes="0=OFF, 1=FX1, 2=FX2, 3=RV3, 4=RV4. "
                        "XL models: 0=PRG (use program setting), 1=OFF, 2=FX1, 3=FX2, 4=RV3, 5=RV4"),
        Parameter("KFXSLEV", 162, 1, "0-99",
                  "Effects send level (keygroup level)"),
        # S3200 second filter and LSI2 parameters
        Parameter("LSI2_ON", 168, 1, "0=-6dB, 1=0dB",
                  "Route audio through second LSI chip",
                  models=["S3200"],
                  notes="S3200 only; enables second filter/processing chain"),
        Parameter("FLT2GAIN", 169, 1, "0=-6dB, 1=0dB",
                  "Make-up gain of second filter",
                  models=["S3200"],
                  notes="S3200 only"),
        Parameter("FLT2MODE", 170, 1, "0=LP, 1=BP, 2=HP, 3=EQ",
                  "Mode of second filter",
                  models=["S3200"],
                  notes="S3200 only; LP=lowpass, BP=bandpass, HP=highpass, EQ=parametric EQ"),
        Parameter("FLT2Q", 171, 1, "0-31",
                  "Resonance of second filter",
                  models=["S3200"],
                  notes="S3200 only"),
        Parameter("TONEFREQ", 172, 1, "0-99",
                  "Center frequency of spectral tilt tone section",
                  models=["S3200"],
                  notes="S3200 only"),
        Parameter("TONESLOP", 173, 1, "-50 to +50",
                  "Slope of spectral tilt tone section",
                  models=["S3200"],
                  notes="S3200 only"),
        Parameter("MODVFLT2_1", 174, 1, "-50 to +50",
                  "Control of filter 2 frequency by assignable source 1",
                  models=["S3200"],
                  notes="S3200 only"),
        Parameter("MODVFLT2_2", 175, 1, "-50 to +50",
                  "Control of filter 2 frequency by assignable source 2",
                  models=["S3200"],
                  notes="S3200 only"),
        Parameter("MODVFLT2_3", 176, 1, "-50 to +50",
                  "Control of filter 2 frequency by assignable source 3",
                  models=["S3200"],
                  notes="S3200 only"),
        Parameter("FIL2FR", 177, 1, "0-99",
                  "Basic second filter frequency",
                  models=["S3200"],
                  notes="S3200 only"),
        Parameter("K_FRQ2", 178, 1, "-24 to +24 semitones",
                  "Second filter key follow",
                  models=["S3200"],
                  notes="S3200 only"),
        # Envelope 3
        Parameter("ATTAK3", 179, 1, "0-99",
                  "Attack rate of envelope 3",
                  notes="Also known as ENV3R1"),
        Parameter("ENV3L1", 180, 1, "0-99",
                  "Final level of attack phase (phase 1) of envelope 3"),
        Parameter("ENV3R2", 181, 1, "0-99",
                  "Rate of phase 2 of envelope 3"),
        Parameter("ENV3L2", 182, 1, "0-99",
                  "Final level of phase 2 of envelope 3"),
        Parameter("DECAY3", 183, 1, "0-99",
                  "Rate of phase 3 (decay) of envelope 3",
                  notes="Also known as ENV3R3"),
        Parameter("SUSTN3", 184, 1, "0-99",
                  "Final level of phase 3 (sustain) of envelope 3",
                  notes="Also known as ENV3L3"),
        Parameter("RELSE3", 185, 1, "0-99",
                  "Rate of release phase (phase 4) of envelope 3",
                  notes="Also known as ENV3R4"),
        Parameter("ENV3L4", 186, 1, "0-99",
                  "Final target level of envelope 3"),
        Parameter("V_ATT3", 187, 1, "-50 to +50",
                  "Velocity dependence of envelope 3 attack rate"),
        Parameter("V_REL3", 188, 1, "-50 to +50",
                  "Velocity dependence of envelope 3 release rate"),
        Parameter("O_REL3", 189, 1, "-50 to +50",
                  "Note-off velocity dependence of envelope 3 release"),
        Parameter("K_DAR3", 190, 1, "-50 to +50",
                  "Key dependence of envelope 3 decay and release rates"),
        Parameter("V_ENV3", 191, 1, "-50 to +50",
                  "Scaling of envelope 3 depth by velocity"),
    ],
)

# ---------------------------------------------------------------------------
# Sample Header (192 bytes, opcode 0x2B/0x2C)
# ---------------------------------------------------------------------------

SAMPLE_HEADER = HeaderSpec(
    name="sample",
    total_size=192,
    request_opcode=0x2B,
    response_opcode=0x2C,
    parameters=[
        Parameter("SHIDENT", 0, 1, "3 (fixed)",
                  "Block identifier for sample headers",
                  notes="Always 3; identifies this block as a sample header"),
        Parameter("SBANDW", 1, 1, "0=10kHz, 1=20kHz",
                  "Sample bandwidth (effective frequency range)"),
        Parameter("SPITCH", 2, 1, "21-127 (A1-G8)",
                  "Original pitch (MIDI note number the sample was recorded at)"),
        Parameter("SHNAME", 3, 12, "Akai string (12 chars)",
                  "Sample name"),
        Parameter("SSRVLD", 15, 1, "0=invalid, 128=valid",
                  "Sample rate validity flag",
                  notes="Set to 128 (0x80) when SSRATE contains a valid sample rate"),
        Parameter("SLOOPS", 16, 1, "0-4",
                  "Number of active loops"),
        Parameter("SALOOP", 17, 1, "0-3",
                  "Index of first active loop (internal)"),
        Parameter("SHLOOP", 18, 1, "0-3",
                  "Index of highest active loop (internal)"),
        Parameter("SPTYPE", 19, 1, "0-3",
                  "Playback type",
                  notes="0=Normal loop, 1=Loop until release, 2=No loop, 3=Play to end"),
        Parameter("STUNO", 20, 2, "cents:semitones",
                  "Sample tuning offset"),
        Parameter("SLOCAT", 22, 4, "Absolute address",
                  "Start address of sample data in memory (internal)",
                  notes="Internal; managed by device"),
        Parameter("SLNGTH", 26, 4, "Data points",
                  "Total sample length in data points"),
        Parameter("SSTART", 30, 4, "Data points",
                  "Playback start offset from beginning of sample"),
        Parameter("SMPEND", 34, 4, "Data points",
                  "Playback end offset"),
        # Loop 1
        Parameter("LOOPAT1", 38, 4, "Data points",
                  "Position of first loop start point"),
        Parameter("LLNGTH1", 42, 6, "Data points (extended precision)",
                  "Length of first loop"),
        Parameter("LDWELL1", 48, 2, "0=no loop, 9999=hold, 1-9998=milliseconds",
                  "Dwell time of first loop"),
        # Loop 2
        Parameter("LOOPAT2", 50, 4, "Data points",
                  "Position of second loop start point"),
        Parameter("LLNGTH2", 54, 6, "Data points (extended precision)",
                  "Length of second loop"),
        Parameter("LDWELL2", 60, 2, "0=no loop, 9999=hold, 1-9998=milliseconds",
                  "Dwell time of second loop"),
        # Loop 3
        Parameter("LOOPAT3", 62, 4, "Data points",
                  "Position of third loop start point"),
        Parameter("LLNGTH3", 66, 6, "Data points (extended precision)",
                  "Length of third loop"),
        Parameter("LDWELL3", 72, 2, "0=no loop, 9999=hold, 1-9998=milliseconds",
                  "Dwell time of third loop"),
        # Loop 4
        Parameter("LOOPAT4", 74, 4, "Data points",
                  "Position of fourth loop start point"),
        Parameter("LLNGTH4", 78, 6, "Data points (extended precision)",
                  "Length of fourth loop"),
        Parameter("LDWELL4", 84, 2, "0=no loop, 9999=hold, 1-9998=milliseconds",
                  "Dwell time of fourth loop"),
        # Loop relative factors
        Parameter("SLXY1", 86, 4, "Internal",
                  "Relative loop factors for loop 1 (internal)",
                  notes="Internal; managed by device"),
        Parameter("SLXY2", 98, 4, "Internal",
                  "Relative loop factors for loop 2 (internal)",
                  notes="Internal; managed by device"),
        Parameter("SLXY3", 110, 4, "Internal",
                  "Relative loop factors for loop 3 (internal)",
                  notes="Internal; managed by device"),
        Parameter("SLXY4", 122, 4, "Internal",
                  "Relative loop factors for loop 4 (internal)",
                  notes="Internal; managed by device"),
        # Miscellaneous
        Parameter("SSPARE", 134, 1, "Internal",
                  "Used internally",
                  notes="Internal; do not modify"),
        Parameter("SWCOMM", 135, 1, "0",
                  "Not used"),
        Parameter("SSPAIR", 136, 2, "Block address",
                  "Address of stereo partner sample (internal)",
                  notes="Internal; managed by device for stereo sample pairs"),
        Parameter("SSRATE", 138, 2, "Hz",
                  "Sample rate in Hertz (e.g. 44100)",
                  notes="Only valid when SSRVLD = 128 (0x80)"),
        Parameter("SHLTO", 140, 1, "-50 to +50",
                  "Tuning offset of hold loop"),
    ],
)

# ---------------------------------------------------------------------------
# All headers in a lookup dictionary
# ---------------------------------------------------------------------------

ALL_HEADERS: dict[str, HeaderSpec] = {
    "program": PROGRAM_HEADER,
    "keygroup": KEYGROUP_HEADER,
    "sample": SAMPLE_HEADER,
}

# ---------------------------------------------------------------------------
# Model Differences Summary
# ---------------------------------------------------------------------------

MODEL_DIFFERENCES = {
    "outputs": {
        "S2800": "2 individual outputs (out1, out2) plus FX send",
        "S3000": "8 individual outputs (out1-out8) plus FX send",
        "S3200": "8 individual outputs (out1-out8) plus FX, RVB, and R+F sends",
    },
    "output_routing_range": {
        "S2800": "OUTPUT (offset 22): 0-2 (0=out1, 1=out2, 2=FX)",
        "S3000": "OUTPUT (offset 22): 0-8 (0-7=outputs 1-8, 8=FX)",
        "S3200": "OUTPUT (offset 22): 0-10 (0-7=outputs, 8=FX, 9=RVB, 10=R+F)",
    },
    "zone_output_range": {
        "S2800": "VZOUT1-4: 0-4",
        "S3000": "VZOUT1-4: 0-10",
        "S3200": "VZOUT1-4: 0-10",
    },
    "filter": {
        "S2800": "Single filter (LP only), no resonance control via SysEx",
        "S3000": "Single filter (LP only) with resonance (FILQ 0-15)",
        "S3200": "Dual filters: Filter 1 (LP) + Filter 2 (LP/BP/HP/EQ), "
                 "each with independent resonance, key follow, and mod sources",
    },
    "second_filter": {
        "S2800": "Not available",
        "S3000": "Not available",
        "S3200": "LSI2_ON (168), FLT2GAIN (169), FLT2MODE (170), FLT2Q (171), "
                 "FIL2FR (177), K_FRQ2 (178), plus mod sources MODSLFLT2_1/2/3 "
                 "and mod amounts MODVFLT2_1/2/3",
    },
    "tone_control": {
        "S2800": "Not available",
        "S3000": "Not available",
        "S3200": "Spectral tilt: TONEFREQ (172), TONESLOP (173)",
    },
    "effects_bus": {
        "S2800": "Program-level FX send only",
        "S3000": "Program-level FX send only",
        "S3200": "Program-level and keygroup-level FX bus select "
                 "(PFXCHAN/KFXCHAN) with FX1, FX2, RV3, RV4 options",
    },
    "reverb": {
        "S2800": "Shared FX/reverb setups",
        "S3000": "50 FX setups",
        "S3200": "50 FX setups + 50 dedicated reverb setups",
    },
    "envelopes": {
        "S2800": "2 envelopes (Env1=amplitude, Env2=filter), 4-stage ADSR",
        "S3000": "2 envelopes (Env1=amplitude, Env2=filter), extended 4-phase",
        "S3200": "3 envelopes (Env1=amplitude, Env2=filter, Env3=auxiliary), "
                 "all with extended 4-phase capability",
    },
}
